version: '3.8'

services:
  entreprises:
    depends_on:
      - mongo
    # image: s/entreprise
    build: ./entreprises
    ports:
      - 3001:3000
    environment:
      - MONGO_URI=mongodb://mongo:27017/entreprises
      - APP_PORT=3000
  
  agents:
    depends_on:
      - mongo
    # image: s/agent
    build: ./agents
    ports:
      - 3002:3000
    environment:
      - MONGO_URI=mongodb://mongo:27017/agents
      - APP_PORT=3000
  
  formateurs:
    depends_on:
      - agents
      - entreprises
    build:
      ./formateurs
    ports:
      - 3003:3000
    environment:
      - MONGO_URI=mongodb://mongo:27017/formateurs
      - APP_PORT=3000
      - AGENTS_URI=http://agents:3000
      - ENTREPRISES_URI=http://entreprises:3000

  competence-query:
    build: ./competences/competence-query
    ports:
      - 3004:3000
    environment:
      - MONGO_URI=mongodb://mongo:27017/competences
      - APP_PORT=3000

  mongo:
    image: mongo
    ports:
      - 27017:27017

  krakend:
    image: devopsfaith/krakend:2.0.5
    ports:
      - 8000:8080
      - 1234:1234
      - 8089:8090
    volumes:
      - ./config/krakend.json:/etc/krakend/krakend.json
      # - ./certs:/etc/krakend/certs
    
  zookeeper:
      image: docker.io/bitnami/zookeeper:3.8
      ports:
        - "2181:2181"
      volumes:
        - "zookeeper_data:/bitnami"
      environment:
        - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.2
    # ⚠ important pour que Kafka puisse accepter localhost en tant qu'adresse de broker
    hostname: localhost
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local