version: '3.8'

services:
  entreprises:
    depends_on:
      - mongo
    # image: s/entreprise
    build: ./entreprises
    ports:
      - 3001:3000
    environment:
      - MONGO_URI=mongodb://mongo:27017/entreprises
      - APP_PORT=3000
  
  agents:
    depends_on:
      - mongo
    # image: s/agent
    build: ./agents
    ports:
      - 3002:3000
    environment:
      - MONGO_URI=mongodb://mongo:27017/agents
      - APP_PORT=3000
  
  formateurs:
    depends_on:
      - agents
      - entreprises
    build:
      ./formateurs
    ports:
      - 3003:3000
    environment:
      - MONGO_URI=mongodb://mongo:27017/formateurs
      - APP_PORT=3000
      - AGENTS_URI=http://agents:3000
      - ENTREPRISES_URI=http://entreprises:3000

  competence-query:
    build: ./competences/competence-query
    ports:
      - 3004:3000
    environment:
      - MONGO_URI=mongodb://mongo:27017/competence
      - APP_PORT=3000

  mongo:
    image: mongo
    ports:
      - 27017:27017

  krakend:
    image: devopsfaith/krakend:2.0.5
    ports:
      - 8000:8080
      - 1234:1234
      - 8089:8090
    volumes:
      - ./config/krakend.json:/etc/krakend/krakend.json
      # - ./certs:/etc/krakend/certs
    
